<?php

namespace ContainerQqvYiqH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7dKqd_KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7dKqd.k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7dKqd.k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', '.errored.pHgTdvt', NULL, 'Cannot determine controller argument for "App\\Controller\\CharacterController::getCharactersByUser()": the $userRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\UserRepository".'],
        ], [
            'userRepository' => '?',
        ]);
    }
}
