<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLzToLty\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLzToLty/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLzToLty.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLzToLty\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLzToLty\App_KernelDevDebugContainer([
    'container.build_hash' => 'LzToLty',
    'container.build_id' => '31b6d192',
    'container.build_time' => 1736292610,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLzToLty');
